apiVersion: v1
kind: Namespace
metadata:
  name: pacman-ns
---
apiVersion: v1
kind: Service
metadata:
  name: pacman-svc
  namespace: pacman-ns
spec:
  type: LoadBalancer
  selector:
    app: pacman-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pacman-app
  name: pacman-app
  namespace: pacman-ns
spec:
  containers:
  - image: chrisley75/nginx-pacman:0.1.5
    name: pacman
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}